packaging_format = 2

id = "pepettes"
name = "Pepettes"
description.en = "A simple donation form with stripe"
description.fr = "Un simple formulaire de don avec stripe"

version = "1.0.1~ynh3"

maintainers = ["ljf"]

[upstream]
license = "MIT"
demo = "https://donate.yunohost.org"
admindoc = "https://github.com/YunoHost/pepettes/blob/main/README.md"
code = "https://github.com/YunoHost/pepettes/"
website = "https://github.com/YunoHost/pepettes/"
cpe = "???" # FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, Yunohost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
fund = "???" # FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.

[integration]
yunohost = ">= 4.1.3"
architectures = "all" # FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
multi_instance = true
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.project_name]
    ask.en = "What's the name of the project which will received donation ?"
    ask.fr = "Quel est le nom du projet qui va recevoir les dons ?"
    type = "string"
    default = ""

    [install.contact_url]
    ask.en = "Indicate a link to contact you to ask for stopping recuring payment"
    ask.fr = "Indiquez un lien pour vous contacter pour arréter les paiements récurrents"
    type = "string"
    default = ""

    [install.logo]
    ask.en = "A link to the logo of your project"
    ask.fr = "Un lien vers le logo de votre projet"
    type = "string"
    default = ""

    [install.favicon]
    ask.en = "A link to the favicon of your project"
    ask.fr = "Un lien vers la favicon de votre projet"
    type = "string"
    default = ""

    [install.publishable_key]
    ask.en = "Indicate here the stripe publishable key"
    ask.fr = "Indiquez ici la clé publique stripe"
    type = "string"
    default = ""

    [install.secret_key]
    ask.en = "Indicate here the stripe secret key"
    ask.fr = "Indiquez ici la clé secrète stripe"
    type = "string"
    default = ""

    [install.prices]
    ask.en = "Indicates here the prices ID of donation products you created in stripe interfaces"
    ask.fr = "Indiquez ici les ID de prix des produits de don stripe que vous avez créé dans l'interface stripe"
    help.en = "Go on https://dashboard.stripe.com/products to create those donation products"
    help.fr = "Allez sur https://dashboard.stripe.com/products pour créer ces produits de dons"
    type = "string"
    default = "one_time/EUR/price_1IKuPV,recuring/EUR/price_1IKuPV"

[resources]
        [resources.sources.main]
        url = "https://github.com/YunoHost/pepettes/archive/v1.0.1.tar.gz"
        sha256 = "9792ed5589d4a55bd619edc7aa61a1a78f34c5a4e7095b2292ac09b66c8b9a58"


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
