#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop" --log_path="systemd"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

ynh_config_add --template="gunicorn.py" --destination="$install_dir/sources/gunicorn.py"
ynh_config_add --template="settings.py" --destination="$install_dir/sources/settings.py"

print_price_ids >> "$install_dir/sources/settings.py"
ynh_store_file_checksum "$install_dir/sources/settings.py"
chown -R "$app:$app" "$install_dir/sources/gunicorn.py" "$install_dir/sources/settings.py"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
