#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================
ynh_script_progression "Setting secret keys..."

secret=$(ynh_string_random --length=50)
csrf_key=$(ynh_string_random --length=50)
ynh_app_setting_set --key="secret" --value="$secret"
ynh_app_setting_set --key="csrf_key" --value="$csrf_key"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/sources"
chown -R "$app:www-data" "$install_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="gunicorn.py" --destination="$install_dir/sources/gunicorn.py"
ynh_config_add --template="settings.py" --destination="$install_dir/sources/settings.py"
ynh_config_add --template="wsgi.py" --destination="$install_dir/sources/wsgi.py"

print_price_ids >> "$install_dir/sources/settings.py"
ynh_store_file_checksum "$install_dir/sources/settings.py"
chown -R "$app:$app" "$install_dir/sources/gunicorn.py" "$install_dir/sources/settings.py" "$install_dir/sources/wsgi.py"

#=================================================
# INSTALL PYTHON DEPENDENCIES
#=================================================
ynh_script_progression "Installing Python dependencies..."

build_python

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --description="Simple donation form" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

ynh_config_add --template="warn-about-attacks-on-donation.sh" --destination="$cron_path"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
