#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

ynh_app_setting_set_default --key=portal_url --value=""

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop" --log_path="systemd"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

ynh_setup_source --dest_dir="$install_dir/sources"
chown -R "$app:www-data" "$install_dir"

#=================================================
# UPGRADE PYTHON DEPENDENCIES
#=================================================
ynh_script_progression "Installing Python dependencies..."

build_python

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

ynh_config_add --template="gunicorn.py" --destination="$install_dir/sources/gunicorn.py"
ynh_config_add --template="settings.py" --destination="$install_dir/sources/settings.py"
ynh_config_add --template="wsgi.py" --destination="$install_dir/sources/wsgi.py"

print_price_ids >> "$install_dir/sources/settings.py"
ynh_store_file_checksum "$install_dir/sources/settings.py"
chown -R "$app:$app" "$install_dir/sources/gunicorn.py" "$install_dir/sources/settings.py" "$install_dir/sources/wsgi.py"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Upgrading systemd configuration..."

ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --description="Simple donation form" --log="/var/log/$app/error.log"

ynh_config_add_logrotate

ynh_config_add --template="warn-about-attacks-on-donation.sh" --destination="$cron_path"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
